services:
  hugo:
    container_name: "hugo"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/portfolio
    tty: true
    develop:
      watch:
        - action: rebuild
          path: /
          target: /portfolio
