baseURL = 'https://carlosdev.co/'
title = 'Carlos Escorcia'
defaultContentLanguage = "en"

[params]
  user = "carlos"
  hostName = "dev"
  
[languages]
  [languages.en]
    weight = 1
    languageName = "English"
    contentDir = "content/en"
    languageCode = "en-us"
  [languages.en.menu]
    [[languages.en.menu.header]]
      name = "blog"
      weight = 0
      url = "blog"
    [[languages.en.menu.header]]
      name = "about"
      weight = 1
      url = "about"

  [languages.es]
    weight = 2
    languageName = "Español"
    contentDir = "content/es"
    languageCode = "es-es"
  [languages.es.menu]
    [[languages.es.menu.header]]
      name = "blog"
      weight = 0
      url = "blog"
    [[languages.es.menu.header]]
      name = "acerca_de"
      weight = 1
      url = "about"

[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'
[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'